{
 "title": "华为交换机监控",
 "description": "For snmp_exporter IF-MIB",
 "tags": [
  "Prometheus",
  "snmp_exporter"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "label_values(ifHCInOctets,  job)"
    }
   },
   {
    "name": "IP",
    "label": "instance",
    "query": {
     "query": "sysName{job=\"$Job\"}"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "ifHCOutOctets{job=\"$Job\",instance=\"$IP\"}"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hwEntityCpuUsage{job=\"$Job\",instance=\"$IP\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hwEntityMemUsage{job=\"$Job\",instance=\"$IP\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "交换机设备风扇状态",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "hwEntityFanSpeed{job=\"$Job\",instance=\"$IP\"}",
     "legendFormat": "风扇{{hwEntityFanSn}}"
    }
   ]
  },
  {
   "title": "温度",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hwEntityTemperature{job=\"$Job\",instance=\"$IP\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "交换机基本信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "交换机型号",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sysName{instance=\"$IP\",job=\"$Job\"}",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Total Out",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCOutOctets{job=\"$Job\"}[$__range]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Total In",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCInOctets{job=\"$Job\"}[$__range]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "天" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max(hwEntityUpTime{instance=\"$IP\",job=\"$Job\"}) or (sysUpTime{instance=\"$IP\",job=\"$Job\"}/100)) /86400> 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Out (Current)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCOutOctets{job=\"$Job\"}[5m]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Max In (Current)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCInOctets{job=\"$Job\"}[5m]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "指定接口流量和-5分钟",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"$Job\",instance=\"$IP\",ifName=~\"$Interface\"}[5m])",
     "legendFormat": "out"
    },
    {
     "expr": "irate(ifHCInOctets{job=\"$Job\",instance=\"$IP\",ifName=~\"$Interface\"}[5m])",
     "legendFormat": "in"
    },
    {
     "expr": "delta(ifHCOutOctets{job=\"$Job\",instance=\"$IP\",ifName=~\"$Interface\"}[$__range])",
     "legendFormat": "total out"
    },
    {
     "expr": "delta(ifHCInOctets{job=\"$Job\",instance=\"$IP\",ifName=~\"$Interface\"}[$__range])",
     "legendFormat": "total in"
    },
    {
     "expr": "ifHighSpeed{job=\"$Job\",instance=\"$IP\",ifName=~\"$Interface\"}",
     "legendFormat": "high speed"
    }
   ]
  },
  {
   "title": "Out / In-指定接口",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "-irate(ifHCOutOctets{job=\"$Job\",instance=\"$IP\",ifName=~\"$Interface\"}[5m])",
     "legendFormat": "Out: {{ifName}} ({{ifAlias}})"
    },
    {
     "expr": "irate(ifHCInOctets{job=\"$Job\",instance=\"$IP\",ifName=~\"$Interface\"}[5m])",
     "legendFormat": "In: {{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "所有接口",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"$Job\",instance=\"$IP\"}[5m])",
     "legendFormat": "out"
    },
    {
     "expr": "irate(ifHCInOctets{job=\"$Job\",instance=\"$IP\"}[5m])",
     "legendFormat": "in"
    },
    {
     "expr": "delta(ifHCOutOctets{job=\"$Job\",instance=\"$IP\"}[$__range])",
     "legendFormat": "total out"
    },
    {
     "expr": "delta(ifHCInOctets{job=\"$Job\",instance=\"$IP\"}[$__range])",
     "legendFormat": "total in"
    },
    {
     "expr": "ifHighSpeed{job=\"$Job\",instance=\"$IP\"}",
     "legendFormat": "high speed"
    }
   ]
  },
  {
   "title": "Out (Current)",
   "type": "bargauge",
   "description": "Max: 100MB  \nRed Status: 90MB",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{instance=\"$IP\",job=\"$Job\"}[5m])>0",
     "legendFormat": "{{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "In (Current)",
   "type": "bargauge",
   "description": "Max: 100MB  \nRed Status: 90MB",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{instance=\"$IP\",job=\"$Job\"}[5m])>0",
     "legendFormat": "{{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Out / In",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "-irate(ifHCOutOctets{instance=\"$IP\",job=\"$Job\"}[5m])",
     "legendFormat": "Out: {{ifName}} ({{ifAlias}})"
    },
    {
     "expr": "irate(ifHCInOctets{instance=\"$IP\",job=\"$Job\"}[5m])",
     "legendFormat": "In: {{ifName}} ({{ifAlias}})"
    }
   ]
  }
 ]
}