{
 "title": "H3C Switch SNMP Dashboard for Prometheus",
 "description": "Prometheus 数据源通过 SNMP Exporter 采集华三园区交换机指标",
 "tags": [
  "huawei",
  "Prometheus",
  "snmp_exporter"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "job", "label": "任务", "query": { "query": "label_values(sysName,job)" } },
   {
    "name": "region",
    "label": "区域",
    "query": {
     "query": "label_values(sysName{job=~\"$job\"},region)"
    }
   },
   {
    "name": "brand",
    "label": "品牌",
    "query": {
     "query": "label_values(sysName{job=~\"$job\", region=~\"$region\"},brand)"
    }
   },
   {
    "name": "role",
    "label": "角色",
    "query": {
     "query": "label_values(sysName{job=~\"$job\", region=~\"$region\", brand=~\"$brand\"},role)"
    }
   },
   {
    "name": "device_ip",
    "label": "实例",
    "query": {
     "query": "query_result(count by (instance) (count_over_time(sysName{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\"}[$__range])))"
    }
   },
   {
    "name": "interface",
    "label": "接口名称",
    "query": {
     "query": "query_result(count by (ifName) (count_over_time(ifHCInOctets{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"}[$__range])))"
    }
   },
   {
    "name": "total",
    "label": "设备总数",
    "query": {
     "query": "query_result(count(sysName{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\"}))"
    }
   },
   { "name": "Filters", "label": "筛选" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "交换机基础信息 - 总数（${total}）", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "总体上行吞吐量 (当前)",
   "type": "stat",
   "description": "该设备上行吞吐量",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ifHCOutOctets{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"}[$__range]) * 8)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "总体下行吞吐量 (当前)",
   "type": "stat",
   "description": "该设备上行吞吐量",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ifHCInOctets{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"}[$__range]) * 8)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "上行总流量",
   "type": "stat",
   "description": "该设备在指定区间内的出站总流量",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ifHCOutOctets{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"}[$__range]) * 8)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "下行总流量",
   "type": "stat",
   "description": "该设备在指定区间内的入站总流量",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ifHCInOctets{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"}[$__range]) * 8)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "当前设备丢包率",
   "type": "stat",
   "description": "该设备总丢包率",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(increase(ifInDiscards{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"}[$__range]))\n  +\n  sum(increase(ifOutDiscards{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"}[$__range]))\n)\n/\n(\n  sum(increase(ifHCInUcastPkts{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"}[$__range]))\n  +\n  sum(increase(ifHCOutUcastPkts{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"}[$__range]))\n)\n* 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "当前设备错包率",
   "type": "stat",
   "description": "该设备总错包率",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(increase(ifInErrors{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"}[$__range]))\n  +\n  sum(increase(ifOutErrors{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"}[$__range]))\n)\n/\n(\n  sum(increase(ifHCInUcastPkts{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"}[$__range]))\n  +\n  sum(increase(ifHCOutUcastPkts{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"}[$__range]))\n)\n* 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "指定接口：{$interface} 上行/下行",
   "type": "timeseries",
   "description": "指定接口流量",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\", ifName=~\"$interface\"}[5m]) * 8",
     "legendFormat": "上行: {{ifName}}"
    },
    {
     "expr": "-irate(ifHCInOctets{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\", ifName=~\"$interface\"}[5m]) * 8",
     "legendFormat": "下行: {{ifName}}"
    }
   ]
  },
  {
   "title": "实体启动时间",
   "type": "table",
   "description": "盒式交换机和框式交换机的部件都是以实体方式存在",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "(hh3cEntityExtUpTime{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} / 86400) * on(instance) group_left(sysName) sysName{sysName!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "设备序列号",
   "type": "table",
   "description": "交换机设备序列号",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "entPhysicalSerialNum{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} * on(instance) group_left(sysName) sysName{sysName!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "软件版本号",
   "type": "stat",
   "description": "交换机当前运行的系统版本号",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "entPhysicalSoftwareRev{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} * on(instance) group_left(sysName) sysName{sysName!=\"\"}",
     "legendFormat": "{{entPhysicalSoftwareRev}}"
    }
   ]
  },
  {
   "title": "板卡状态",
   "type": "stat",
   "description": "盒式交换机的板卡当前状态",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hh3cEntityExtErrorStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} * on(instance) group_left(sysName) sysName{sysName!=\"\"}",
     "legendFormat": "{{entPhysicalName}}"
    }
   ]
  },
  {
   "title": "电源供电状态",
   "type": "stat",
   "description": "当前设备电源供电状态",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hh3cDevMPowerStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} * on(instance) group_left(sysName) sysName{sysName!=\"\"}",
     "legendFormat": "{{sysName}} 编号-{{hh3cDevMPowerNum}}"
    }
   ]
  },
  {
   "title": "风扇运行状态",
   "type": "stat",
   "description": "当前设备风扇运行状态",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hh3cDevMFanStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} * on(instance) group_left(sysName) sysName{sysName!=\"\"}",
     "legendFormat": "{{sysName}}  编号-{{hh3cDevMFanNum}}"
    }
   ]
  },
  {
   "title": "CPU 使用率",
   "type": "gauge",
   "description": "当前交换机设备 CPU 使用率",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hh3cEntityExtCpuUsage{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} * on(instance) group_left(sysName) sysName{sysName!=\"\"}",
     "legendFormat": "{{entPhysicalName}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "gauge",
   "description": "当前交换机设备内存使用率",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hh3cEntityExtMemUsage{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} * on(instance) group_left(sysName) sysName{sysName!=\"\"}",
     "legendFormat": "{{entPhysicalName}}"
    }
   ]
  },
  {
   "title": "实时温度",
   "type": "stat",
   "description": "当前交换机实体部件温度",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hh3cEntityExtTemperature{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} * on(instance) group_left(sysName) sysName{sysName!=\"\"}",
     "legendFormat": "{{entPhysicalName}}"
    }
   ]
  },
  {
   "title": "MAC 表项使用率",
   "type": "stat",
   "description": "设备 MAC 表项使用数量除以交换机限制总数",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (instance) (\n    hh3cEntityExtMacAddressCount{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"}\n  )\n)\n/\n(\n  sum by (instance) (\n    hh3cMaxMacLearnRange{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"}\n  )\n)\n* on(instance) group_left(sysName) sysName{sysName!=\"\"}",
     "legendFormat": "{{sysName}}"
    }
   ]
  },
  {
   "title": "存储使用率",
   "type": "gauge",
   "description": "交换机设备存储使用率",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((hh3cFlhPartSpace{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} - hh3cFlhPartSpaceFree{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"}) / hh3cFlhPartSpace{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"}  * 100) * on(instance) group_left(sysName) sysName{sysName!=\"\"}",
     "legendFormat": "{{hh3cFlhPartName}}"
    }
   ]
  },
  {
   "title": "设备存储容量",
   "type": "table",
   "description": "交换机设备存储容量情况",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "hh3cFlhPartStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} * on(instance) group_left(sysName) sysName{sysName!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hh3cFlhPartSpaceFree{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} * on(instance) group_left(sysName) sysName{sysName!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hh3cFlhPartSpace{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} * on(instance) group_left(sysName) sysName{sysName!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "接口信息汇总",
   "type": "table",
   "description": "设备接口信息",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "ifOperStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} * on(instance) group_left(sysName) sysName{sysName!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(ifHCOutOctets{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} * on(instance) group_left(sysName) sysName{sysName!=\"\"}[5m]) * 8",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(ifHCInOctets{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} * on(instance) group_left(sysName) sysName{sysName!=\"\"}[5m]) * 8",
     "legendFormat": "__auto"
    },
    {
     "expr": "ifHighSpeed{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} * on(instance) group_left(sysName) sysName{sysName!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "交换机汇总【总数：$total】",
   "type": "table",
   "description": "交换机汇总信息",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "(hh3cEntityExtUpTime{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\"} / 86400) * on(instance) group_left(sysName) sysName{sysName!=\"\"}",
     "legendFormat": "启动(天)"
    },
    {
     "expr": "hh3cEntityExtCpuUsage{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\"} * on(instance) group_left(sysName) sysName{sysName!=\"\"}",
     "legendFormat": "CPU 使用率"
    },
    {
     "expr": "hh3cEntityExtMemUsage{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\"} * on(instance) group_left(sysName) sysName{sysName!=\"\"}",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "sysName{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\"} * on(instance) group_left(sysName) sysName{sysName!=\"\"}",
     "legendFormat": "PING 连通性"
    }
   ]
  },
  {
   "title": "交换机接口信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "指定接口流量和 - 5分钟",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "irate(ifHCOutOctets{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\", ifName=~\"$interface\"}[5m]) * 8",
       "legendFormat": "上行带宽"
      },
      {
       "expr": "irate(ifHCInOctets{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\", ifName=~\"$interface\"}[5m]) * 8",
       "legendFormat": "下行带宽"
      },
      {
       "expr": "ifHCOutOctets{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\", ifName=~\"$interface\"} * 8",
       "legendFormat": "总上行流量"
      },
      {
       "expr": "ifHCInOctets{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\", ifName=~\"$interface\"} * 8",
       "legendFormat": "总下行流量"
      },
      {
       "expr": "ifHighSpeed{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\", ifName=~\"$interface\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "ifOperStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\", ifName=~\"$interface\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "指定接口：{$interface} 上行/下行",
     "type": "timeseries",
     "description": "指定接口流量",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(ifHCOutOctets{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\", ifName=~\"$interface\"}[5m]) * 8",
       "legendFormat": "上行: {{ifName}}"
      },
      {
       "expr": "-irate(ifHCInOctets{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\", ifName=~\"$interface\"}[5m]) * 8",
       "legendFormat": "下行: {{ifName}}"
      }
     ]
    },
    {
     "title": "上行带宽占用率（当前-Top10）",
     "type": "bargauge",
     "description": "当前交换机接口（5分钟内）带宽占用率排序前十",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, irate(ifHCOutOctets{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"}) / (ifHighSpeed{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} * 1000))",
       "legendFormat": "{{ifName}}        "
      }
     ]
    },
    {
     "title": "下行带宽占用率（当前-Top10）",
     "type": "bargauge",
     "description": "当前交换机接口（5分钟内）带宽使用率排序前十",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, irate(ifHCInOctets{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"}) / (ifHighSpeed{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} * 1000))",
       "legendFormat": "{{ifName}}"
      }
     ]
    },
    {
     "title": "上行（当前-Top10）",
     "type": "bargauge",
     "description": "当前交换机接口流量排序前十",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, irate(ifHCOutOctets{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"}[5m]) * 8)",
       "legendFormat": "{{ifName}}        "
      }
     ]
    },
    {
     "title": "下行（当前-Top10）",
     "type": "bargauge",
     "description": "当前交换机接口流量排序前十",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, irate(ifHCInOctets{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"}[5m]) * 8)",
       "legendFormat": "{{ifName}}        "
      }
     ]
    }
   ]
  },
  {
   "title": "光模块信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "光模块状态",
     "type": "table",
     "description": "当前交换机中存在的光模块信息",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "hh3cTransceiverHardwareType{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"}  * on(instance) group_left(sysName) sysName{sysName!=\"\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "(hh3cTransceiverCurRXPower{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} / 100) * on(instance) group_left(sysName) sysName{sysName!=\"\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "(hh3cTransceiverCurTXPower{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} / 100) * on(instance) group_left(sysName) sysName{sysName!=\"\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "(\n    # 主计算分支：值>0时的正确计算\n    10 * log10(\n        ((hh3cTransceiverRcvPwrHiWarn{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} > 0) / 1000)\n    )\n    # 关联sysName标签\n    * on(instance) group_left(sysName) sysName{sysName!=\"\"}\n)\nor \n(\n    # 零值分支：值<=0时返回0并携带标签\n    (hh3cTransceiverRcvPwrHiWarn{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} <= 0)\n    # 关联标签并强制返回0\n    * on(instance) group_left(sysName) sysName{sysName!=\"\"} \n    * 0 \n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "(\n    # 主计算分支：值>0时的正确计算\n    10 * log10(\n        ((hh3cTransceiverRcvPwrLoWarn{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} > 0) / 1000)\n    )\n    # 关联sysName标签\n    * on(instance) group_left(sysName) sysName{sysName!=\"\"}\n)\nor \n(\n    # 零值分支：值<=0时返回0并携带标签\n    (hh3cTransceiverRcvPwrLoWarn{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} <= 0)\n    # 关联标签并强制返回0\n    * on(instance) group_left(sysName) sysName{sysName!=\"\"} \n    * 0 \n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "(\n    # 主计算分支：值>0时的正确计算\n    10 * log10(\n        ((hh3cTransceiverPwrOutHiWarn{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} > 0) / 1000)\n    )\n    # 关联sysName标签\n    * on(instance) group_left(sysName) sysName{sysName!=\"\"}\n)\nor \n(\n    # 零值分支：值<=0时返回0并携带标签\n    (hh3cTransceiverPwrOutHiWarn{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} <= 0)\n    # 关联标签并强制返回0\n    * on(instance) group_left(sysName) sysName{sysName!=\"\"} \n    * 0 \n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "(\n    # 主计算分支：值>0时的正确计算\n    10 * log10(\n        ((hh3cTransceiverPwrOutLoWarn{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} > 0) / 1000)\n    )\n    # 关联sysName标签\n    * on(instance) group_left(sysName) sysName{sysName!=\"\"}\n)\nor \n(\n    # 零值分支：值<=0时返回0并携带标签\n    (hh3cTransceiverPwrOutLoWarn{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} <= 0)\n    # 关联标签并强制返回0\n    * on(instance) group_left(sysName) sysName{sysName!=\"\"} \n    * 0 \n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "hh3cTransceiverTemperature{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} * on(instance) group_left(sysName) sysName{sysName!=\"\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "hh3cTransceiverWaveLength{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} * on(instance) group_left(sysName) sysName{sysName!=\"\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "hh3cTransceiverType{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} * on(instance) group_left(sysName) sysName{sysName!=\"\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "(hh3cTransceiverVoltage{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} / 100) * on(instance) group_left(sysName) sysName{sysName!=\"\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "(hh3cTransceiverBiasCurrent{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=~\"$device_ip\"} / 100) * on(instance) group_left(sysName) sysName{sysName!=\"\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}